Update ci-release.yml

diff --git a/.github/workflows/ci-release.yml b/.github/workflows/ci-release.yml
--- a/.github/workflows/ci-release.yml
+++ b/.github/workflows/ci-release.yml
@@ -26,24 +26,23 @@ jobs:
         uses: actions/checkout@v4
       - name: Increase build
         run: |
-         #echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV
-         #gh secret list
-         #gh secret list -e prod 
-         #gh secret delete MASTER_CONTROLLER_NAME -e prod
-         #gh secret list -e prod
-         gh secret list -e prod --json | jq '.[] | select(.name == "MASTER_CONTROLLER_NAME").name' > /dev/null
-         if [ $? -eq 0 ]; then
-           echo "Secret exists, deleting..."
-           gh secret delete MASTER_CONTROLLER_NAME -e prod
-           if [ $? -eq 0 ]; then
-             echo "Secret deleted successfully."
-           else
-             echo "Failed to delete secret."
-           fi
-         else
-           echo "Secret does not exist."
-         fi
-    
+            secrets_to_delete=(MASTER_CONTROLLER_IP SLAVE_CONTROLLER_IPS SLAVE_CONTROLLER_NAMES WILDFLY_HOSTNAME WILDFLY_PASSWORD WILDFLY_PORT	WILDFLY_USERNAME)
+            list_secret_names=$(gh secret list -e prod | awk '{print $1}')
+            for secret_name in "${secrets[@]}"; do
+              if [[ "$list_secret_names" =~ "$secret_name" ]]; then  # Check if MY_SECRET exists in the list
+                echo "Secret exists, deleting..."
+                gh secret delete $secret_name -e prod
+                if [ $? -eq 0 ]; then
+                  echo "Secret deleted successfully."
+                else
+                  echo "Failed to delete secret."
+                fi
+              else
+                echo "Secret does not exist."
+              fi
+            done
+            echo "below"
+            gh secret list -e prod
       # - name: Create Prerelease
       #   uses: ncipollo/release-action@v1
       #   with:
